const classifiedKeywords = {
    "variables": {
        "var": "متغير",
        "let": "لنفرض",
        "const": "ثابت",
    },
    "function": {
        "function": "داله",
        "return": "الجواب",
        "yield": "نتيجه",
        "arguments": "مدخلات",
    },
    "boolean": {
        "true": "صحيح",
        "false": "خطا",
    },
    "if": {
        "if": "اذا",
        "else": "والا",
    },
    "loops": {
        "for": "؟",
        "of": "من",
        "in": "داخل",
        "while": "مادام",
        "do": "افعل",
        "break": "قف",
        "continue": "استمر",
    },
    "switch": {
        "switch": "حالات",
        "case": "حاله",
        "default": "افتراضي",
    },
    "try": {
        "try": "حاول",
        "catch": "التقط",
        "finally": "نهائي",
        "throw": "اخبر",
    },
    "oop": {
        "class": "מחלקה",
        "this": "אנוכי",
        "new": "انشى",
        "null": "כלום",
        "extends": "מרחיבה",
        "super": "אמא",
        "instanceof": "מסוג",
        "static": "נייח",
    },
    "other": {
        "delete": "השמידי",
        "typeof": "סוגשל",
        "goto": "לכיאל",
        "eval": "שערכי",
        "with": "עם",
        "debugger": "تفحص",
        "import": "استورد",
        "export": "اصدر",
        "as": "الى",
        "from": "من"
    },
    "safety": {
        "package": "חבילה",
        "interface": "ממשק",
        "implements": "מיישמת",
        "private": "פרטי",
        "protected": "מוגן",
        "public": "פומבי",
        "native": "יליד",
        "synchronized": "מתואם",
        "throws": "זורק",
        "transient": "חולף",
        "void": "ריק",
        "volatile": "תנודתי",
        "enum": "מנייה",
        "final": "סופי",
    },
    "types": {
        "float": "عشري",
        "int": "رقم",
        "long": "ארוך",
        "char": "תו",
        "short": "קצר",
        "double": "דובל",
        "byte": "بايت",
        "boolean": "בוליאן",
    },
};
const classifiedDictionary = {
    "generic": {
        "console": "اطبع",
        "undefined": "مجهول",
        "NaN": "لارقمي",
        "Infinity": "لانهائي",
        "JSON": "جيسون",
        "prototype": "אבטיפוס",
        "constructor": "בנאי",
        "eval": "שערכי",
        "window": "חלון",
        "document": "מסמך",
        "fetch": "حمل",
        "json": "الى_جيسون"

    },
    "functions": {
        "setTimeout": "קבעי_תזמון",
        "clearTimeout": "בטלי_תזמון",
        "setInterval": "קבעי_חזרתיות",
        "clearInterval": "בטלי_חזרתיות",
        "parseFloat": "נתחי_צף",
        "parseInt": "נתחי_שלם",
        "isFinite": "האם_סופי",
        "isNaN": "رقمي",
        "decodeURI": "פענחי_כתובת_אתר",
        "decodeURIComponent": "פענחי_רכיב_כתובת_אתר",
        "encodeURI": "קודדי_כתובת_אתר",
        "encodeURIComponent": "קודדי_רכיב_כתובת_אתר",
        "escape": "בצעי_בריחה",
        "unescape": "בטלי_בריחה",
        "require": "דרשי",

    },
    "classes": {
        "Object": "עצם",
        "Function": "היכולת",
        "Boolean": "הבוליאן",
        "Number": "מספר",
        "Date": "תאריך",
        "String": "המחרוזת",
        "RegExp": "ביטוי_סדיר",
        "Array": "מערך",
        "Buffer": "חיץ",
        "Set": "קבוצה",
        "Map": "מפה",
        "Promise": "הבטחה",
        "Math": "חשבון",
    },
    "console": {
        "error": "خلل",
        "log": "نص",
        "clear": "נקה",
        "debug": "ניפוי",
        "info": "معلومة",
        "trace": "עקבות",
        "warn": "تنبية",
        "table": "جدول"
    },
    "json": {
        "stringify": "מחרז",
        "parse": "פענח",
    },
    "promise": {
        "reject": "رفض",
        "resolve": "قبول",
        "all": "كل",
        "race": "تعارض",
        "then": "ثم",
        "catch": "فشل",
    },
    "math": {
        "abs": "ערך_מוחלט",
        "ceil": "תקרה",
        "floor": "רצפה",
        "max": "מירבי",
        "min": "מזערי",
        "pow": "חזקה",
        "random": "عشوائي",
        "round": "עגל",
        "sqrt": "שורש",
    },
    "array": {
        "concat": "جمع",
        "length": "طول",
        "entries": "רשומות",
        "filter": "صفي",
        "find": "اوجد",
        "forEach": "لكل",
        "includes": "يوجد",
        "indexOf": "מספר_סידורי_של",
        "join": "צרף",
        "keys": "מפתחות",
        "lastIndexOf": "מספר_סידורי_אחרון_של",
        "map": "نقح",
        "pop": "שלוף",
        "push": "דחוף",
        "reduce": "צמצם",
        "reverse": "הפוך",
        "shift": "הסט",
        "slice": "פרוס",
        "some": "כלשהו",
        "sort": "رتب",
        "splice": "אחה",
        "toString": "למחרוזת",
        "unshift": "בטל_הסט",
    },
    "string": {
        "charAt": "תו_ב",
        "charCodeAt": "קוד_תו_ב",
        "endsWith": "מסתיים_ב",
        "match": "התאם",
        "repeat": "חזור",
        "replace": "החלף",
        "search": "חפש",
        "split": "פצל",
        "startsWith": "מתחיל_ב",
        "substr": "תת_מחרוז",
        "substring": "תת_מחרוזת",
        "trim": "קצץ",
    },
};

function flattenObject(obj) {
    const result = {};
    for (const k in obj) {
        const nested = obj[k];
        for (const key in nested) {
            const value = nested[key];
            result[key] = value;
        }
    }
    return result;
}

export default {
    keywords: flattenObject(classifiedKeywords),
    dictionary: flattenObject(classifiedDictionary),
    chars: {
        "ا": "a",
        "ب": "b",
        "ج": "g",
        "د": "d",
        "ه": "h",
        "ו": "v",
        "ז": "z",
        "ח": "h",
        "ט": "t",
        "י": "i",
        "כ": "k",
        "ל": "l",
        "מ": "m",
        "נ": "n",
        "ס": "s",
        "ע": "a",
        "פ": "p",
        "צ": "z",
        "ק": "k",
        "ר": "r",
        "ש": "sh",
        "ת": "t",
        "ן": "n",
        "ם": "m",
        "ך": "ch",
        "ף": "f",
        "ץ": "z"
    },
    quotes: [
        '"',
        "'",
        "״",
        "׳",
    ],
    classifiedKeywords,
    classifiedDictionary,
}
